version: 2
jobs:
    build-latest: &common-build
        docker:
            - image: node:latest
        steps:
            - checkout
            - restore_cache:
                key: dependencies-{{ .Branch }}
            - run: npm install
            - save_cache:
                key: dependencies-{{ .Branch }}
                paths:
                    - node_modules
            - run: npm test
            - store_artifacts:
                path: coverage

    build-v18:
        <<: *common-build
        docker:
            - image: node:18

    build-v20:
        <<: *common-build
        docker:
            - image: node:20

workflows:
    version: 2
    build_and_test:
        jobs:
            - build-latest
            - build-v18
            - build-v20
